'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowUpRight,ArrowRight,Eye,EyeOff,LoaderCircle,ShieldCheck,Users,GraduationCap,BriefcaseBusiness,Mail,LockKeyhole,UserRound,Check,CheckCircle2,AlertCircle} from 'lucide-react';
import {Brand} from './brand';
import {CampusExperience} from './campus-experience';
export function AuthScreen({mode,demo}:{mode:'login'|'signup';demo:boolean}){
 const router=useRouter();const signup=mode==='signup';
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [name,setName]=useState('');
 const [role,setRole]=useState<'student'|'employee'>('student');
 const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [caps,setCaps]=useState(false);const [signedOut,setSignedOut]=useState(false);
 useEffect(()=>{if(sessionStorage.getItem('loop-signed-out')){setSignedOut(true);sessionStorage.removeItem('loop-signed-out');}},[]);
 async function submit(event:FormEvent){event.preventDefault();setError('');if(signup&&password!==confirm){setError('Your passwords do not match. Please check them.');return;}setBusy(true);
  try{const response=await fetch('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,name,role})});
   const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again.');router.replace('/dashboard');router.refresh();
  }catch(e){setError(e instanceof Error?e.message:'Please try again.');setBusy(false);}
 }
 return <main className="auth-layout"><section className="auth-story"><Brand/><div className="auth-story-body"><span className="story-pill"><span/>BUILT FOR YOUR EVERYDAY</span><h1>Go places.<br/>Stay <span>connected.</span></h1><p>Small rides. Stronger connections.<br/>One campus. Three stops. Your people.</p><CampusExperience/></div><footer><span className="company-signature"><strong>Loop Interactive</strong><br/>Inspiring mobility and technology.</span>Made and maintained by Subendu Kundu — Principal Engineer and Hemant Kumar Rawani — Lead Engineer.<span className="copyright">© 2026 Loop Interactive. All rights reserved.</span><ArrowUpRight size={16}/></footer></section>
 <section className="auth-form-area"><div className="auth-mobile-brand"><Brand/></div><div className="auth-form-wrap"><nav className="auth-tabs" aria-label="Account access"><Link href="/login" aria-current={!signup?'page':undefined}>Sign in</Link><Link href="/signup" aria-current={signup?'page':undefined}>Create account</Link></nav><div className="auth-heading-icon">{signup?<UserRound size={24}/>:<ArrowUpRight size={25}/>}</div><span className="eyebrow">{signup?'YOUR JOURNEY STARTS HERE':'GOOD TO SEE YOU AGAIN'}</span><h2>{signup?'Make yourself at home.':'Your next move.'}</h2><p className="muted">{signup?'Your next campus ride is just an account away.':'Sign in. Pick your stop. We’ll take it from there.'}</p>
 {signedOut&&!signup&&<div className="auth-success" role="status"><CheckCircle2 size={17}/>You’re signed out. See you on your next ride.</div>}
 <form onSubmit={submit} className="auth-form" aria-busy={busy}>
 <fieldset disabled={busy} className="auth-fields">
 {signup&&<><label className="field-label" htmlFor="account-name">Full name</label><div className="auth-input"><UserRound size={17}/><input id="account-name" autoComplete="name" required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></div><div className="role-field"><span className="field-label">I’m joining as</span><div className="role-picker"><button type="button" aria-pressed={role==='student'} className={role==='student'?'selected':''} onClick={()=>setRole('student')}><GraduationCap size={19}/><span>Student<small>Study. Ride. Repeat.</small></span>{role==='student'&&<Check size={14}/>}</button><button type="button" aria-pressed={role==='employee'} className={role==='employee'?'selected':''} onClick={()=>setRole('employee')}><BriefcaseBusiness size={19}/><span>Employee<small>A smoother workday.</small></span>{role==='employee'&&<Check size={14}/>}</button></div></div></>}
 <label className="field-label" htmlFor="account-email">Email address</label><div className="auth-input"><Mail size={17}/><input id="account-email" type="email" autoComplete="email" required maxLength={160} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div>
 <label className="field-label" htmlFor="account-password">Password</label><div className="auth-input"><LockKeyhole size={17}/><input id="account-password" type={show?'text':'password'} autoComplete={signup?'new-password':'current-password'} required minLength={signup?10:1} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} onKeyUp={e=>setCaps(e.getModifierState('CapsLock'))} onBlur={()=>setCaps(false)} aria-describedby={signup?'password-guidance':undefined} placeholder={signup?'Create a password':'Enter your password'}/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'} aria-pressed={show}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>
 {caps&&<p className="field-hint caps-hint"><AlertCircle size={13}/>Caps Lock is on</p>}
 {signup&&<><p id="password-guidance" className={'field-hint '+(password.length>=10?'valid':'')}><Check size={13}/>Use at least 10 characters.</p><label className="field-label" htmlFor="confirm-password">Confirm password</label><div className="auth-input"><LockKeyhole size={17}/><input id="confirm-password" type={show?'text':'password'} autoComplete="new-password" required maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Enter your password again"/>{confirm&&confirm===password&&<CheckCircle2 size={17} className="valid"/>}</div></>}
 {error&&<div className="form-error" role="alert"><AlertCircle size={16}/>{error}</div>}
 <button className="button primary full-width auth-submit" disabled={busy}>{busy?<><LoaderCircle size={18} className="spin"/>{signup?'Creating your account…':'Signing you in…'}</>:<>{signup?'Create my account':'Sign in'}<ArrowRight size={18}/></>}</button></fieldset></form>
 <p className="auth-switch">{signup?'Already part of the campus?':'Your first ride with us?'} <Link href={signup?'/login':'/signup'}>{signup?'Sign in':'Create an account'}</Link></p>
 {!signup&&demo&&<div className="demo-accounts"><span className="eyebrow">TRY A LOCAL DEMO ACCOUNT</span><div>{['student','employee','rider'].map(account=><button key={account} type="button" onClick={()=>{setEmail(account+'@loop.demo');setPassword('CampusRide!2026');setError('');}}>{account==='student'?<GraduationCap size={15}/>:account==='employee'?<Users size={15}/>:<ArrowUpRight size={15}/>}<span>{account}</span></button>)}</div><small>Local MongoDB · sample accounts only</small></div>}
 <details className="auth-how"><summary>How does a campus ride work?<ArrowUpRight size={15}/></summary><ol><li><span>01</span>Choose your stops and departure time.</li><li><span>02</span>The rider accepts and reserves the Toto.</li><li><span>03</span>Board, arrive, and find the trip in your history.</li></ol></details><div className="auth-trust"><ShieldCheck size={15}/><span>Private account. Personal trip history.</span></div><p className="auth-role-note">Students, employees and riders sign in here.</p><Link className="auth-about-link" href="/about">Meet the people behind Loop<ArrowUpRight size={12}/></Link></div></section></main>;
}
