'use client';
import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowRight,ArrowUpRight,ArrowDownLeft,Check,CheckCheck,ChevronDown,ChevronRight,Clock3,History,Home,LoaderCircle,LogOut,MapPin,Plus,Search,ShieldCheck,Users,X,CalendarDays,AlertCircle,BusFront,CheckCircle2,Minus,RefreshCw} from 'lucide-react';
import {Brand,TotoArt} from './brand';
import {CampusExperience} from './campus-experience';
import {LOCATIONS,type PublicUser,type BookingView,type BookingStatus} from '@/lib/types';
type View='overview'|'history'|'about';
const labels:Record<BookingStatus,string>={pending:'Awaiting rider',accepted:'Confirmed',conflict:'Slot unavailable',in_progress:'In progress',completed:'Completed'};
const dateText=(value:string)=>new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short',timeZone:'Asia/Kolkata'});
const timeText=(value:string)=>new Date(value).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit',timeZone:'Asia/Kolkata'});
function todayIST(){return new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Asia/Kolkata'}).format(new Date());}
function initials(name:string){return name.trim().split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase();}
async function api(path:string,method='GET',data?:unknown){const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const body=await response.json();if(!response.ok)throw new Error(body.error||(body.conflict?'This slot is already reserved.':'Please try again.'));return body;}
function Status({status}:{status:BookingStatus}){return <span className={'status status-'+status}><i/>{labels[status]}</span>;}
export function Dashboard({user,initialBookings,slotMinutes,demo}:{user:PublicUser;initialBookings:BookingView[];slotMinutes:number;demo:boolean}){
 const router=useRouter();const rider=user.role==='rider';
 const [bookings,setBookings]=useState(initialBookings);const [view,setView]=useState<View>('overview');
 useEffect(()=>{window.scrollTo(0,0);},[view]);
 const [filter,setFilter]=useState('all');const [tripSearch,setTripSearch]=useState('');const [selected,setSelected]=useState<string|null>(null);const [busy,setBusy]=useState<string|null>(null);
 const [refreshing,setRefreshing]=useState(false);const [accountOpen,setAccountOpen]=useState(false);
 useEffect(()=>{if(!accountOpen)return;const close=(event:MouseEvent)=>{if(!(event.target as HTMLElement).closest('.account-control'))setAccountOpen(false);};const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setAccountOpen(false);document.getElementById('account-toggle')?.focus();}};document.addEventListener('click',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('click',close);document.removeEventListener('keydown',key);};},[accountOpen]);
 const [notice,setNotice]=useState<{text:string;error:boolean}|null>(null);
 async function refresh(){try{const data=await api('/api/bookings');setBookings(data.bookings);}catch{/* Keep current data on transient refresh failures. */}}
 useEffect(()=>{const interval=setInterval(refresh,15000);const focus=()=>{void refresh();};window.addEventListener('focus',focus);return()=>{clearInterval(interval);window.removeEventListener('focus',focus);};},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(null),7000);return()=>clearTimeout(timer);},[notice]);
 const active=bookings.find(b=>b.status==='in_progress');
 const next=bookings.filter(b=>['accepted','in_progress'].includes(b.status)).sort((a,b)=>a.startsAt.localeCompare(b.startsAt))[0];
 const history=bookings.filter(b=>b.status==='completed');
 const display=useMemo(()=>{let result=view==='history'?history:bookings.filter(b=>b.status!=='completed');if(filter!=='all')result=result.filter(b=>b.status===filter);if(tripSearch.trim()){const q=tripSearch.toLowerCase();result=result.filter(b=>[b.origin,b.destination,b.requesterName,...b.passengers.map(p=>p.name)].some(value=>value.toLowerCase().includes(q)));}return [...result].sort((a,b)=>view==='history'?b.startsAt.localeCompare(a.startsAt):a.startsAt.localeCompare(b.startsAt));},[bookings,view,filter,tripSearch]);
 const detail=bookings.find(b=>b._id===selected);
 const boarded=rider?history.reduce((total,b)=>total+b.passengers.filter(p=>p.status==='boarded').length,0):history.filter(b=>b.passengers.find(p=>p.userId===user._id)?.status==='boarded').length;
 async function tripAction(id:string,action:string,extra?:Record<string,unknown>){setBusy(id+action);try{await api('/api/bookings/'+id,'PATCH',{action,...extra});await refresh();setNotice({text:action==='accept'?'Ride accepted. The Toto is reserved.':action==='start'?'Pickup started. Mark each passenger.':action==='complete'?'Trip completed. Boarding records are saved.':'Passenger status saved.',error:false});}catch(e){setNotice({text:e instanceof Error?e.message:'Please try again.',error:true});await refresh();}finally{setBusy(null);}}
 async function manualRefresh(){setRefreshing(true);try{const data=await api('/api/bookings');setBookings(data.bookings);setNotice({text:'Your trips are up to date.',error:false});}catch(e){setNotice({text:e instanceof Error?e.message:'Could not refresh your trips.',error:true});}finally{setRefreshing(false);}}
 async function logout(){setBusy('logout');try{await api('/api/auth/logout','POST',{});sessionStorage.setItem('lawazia-signed-out','1');router.replace('/login');router.refresh();}catch(e){setNotice({text:e instanceof Error?e.message:'Please try again.',error:true});setBusy(null);}}
 function switchView(value:View){setView(value);setFilter('all');setTripSearch('');}
 return <div className="app-shell"><aside className="sidebar"><Brand/><div className="sidebar-section-label">YOUR CAMPUS</div><nav><button onClick={()=>switchView('overview')} className={view==='overview'?'nav-link active':'nav-link'}><Home size={19}/>{rider?'Ride requests':'Overview'}<ChevronRight size={15}/></button><button onClick={()=>switchView('history')} className={view==='history'?'nav-link active':'nav-link'}><History size={19}/>{rider?'Trip log':'My history'}<ChevronRight size={15}/></button><button onClick={()=>switchView('about')} className={view==='about'?'nav-link active':'nav-link'}><ShieldCheck size={19}/>About Lawazia<ChevronRight size={15}/></button></nav><div className="sidebar-bottom"><div className="campus-note"><span className="small-logo"><BusFront size={18}/></span><div><strong>One Toto. Three stops.</strong><span>Lawazia campus</span></div></div><div className="sidebar-user"><span className="avatar">{initials(user.name)}</span><div><strong>{user.name}</strong><span>{user.role}</span></div><button onClick={logout} disabled={busy==='logout'} title="Sign out" aria-label="Sign out">{busy==='logout'?<LoaderCircle size={18} className="spin"/>:<LogOut size={18}/>}</button></div></div></aside>
 <div className="workspace"><header className="topbar"><div className="mobile-brand"><Brand/></div><span className="breadcrumb">Your campus <ChevronRight size={13}/> <strong>{view==='about'?'About Lawazia':view==='history'?(rider?'Trip log':'My history'):(rider?'Ride requests':'Overview')}</strong></span><div className="topbar-right"><button className="refresh-button" onClick={manualRefresh} disabled={refreshing} aria-label="Refresh trips" title="Refresh trips"><RefreshCw size={14} className={refreshing?'spin':''}/><span>{refreshing?'Refreshing…':'Refresh'}</span></button>{demo&&<span className="local-pill">LOCAL DEMO</span>}<span className="topbar-date"><CalendarDays size={15}/>{new Date().toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kolkata'})}</span><div className="account-control"><button id="account-toggle" className="account-toggle" onClick={()=>setAccountOpen(!accountOpen)} aria-expanded={accountOpen} aria-controls="account-menu" aria-label="Your account"><span className="avatar small">{initials(user.name)}</span><span className="account-label">{user.name.split(" ")[0]}<small>{user.role}</small></span><ChevronDown size={13}/></button>{accountOpen&&<div id="account-menu" className="account-menu"><strong>{user.name}</strong><span>{user.email}</span><small>{user.role} account</small><button onClick={logout} disabled={busy==='logout'}>{busy==='logout'?<LoaderCircle size={16} className="spin"/>:<LogOut size={16}/>} {busy==='logout'?'Signing out…':'Sign out'}</button></div>}</div></div></header>
 <main className="main-content"><div className="page-heading"><div><span className="eyebrow">{rider?'BEHIND THE WHEEL':'MOVE AROUND CAMPUS'}</span><h1>{view==='about'?'Small rides. Shared ambition.':view==='history'?(rider?'Every ride, recorded.':'Your campus journeys.'):(rider?'Keep the campus moving.':'Your next move, '+user.name.split(' ')[0]+'.')}</h1><p>{view==='about'?'Meet the people behind your campus connection.':view==='history'?'A permanent record of trips and individual boarding.':rider?'Review requests, manage pickup, and keep the campus moving.':'College, station, or office. Your next ride starts here.'}</p></div><span className="campus-tag"><span/>LAWAZIA CAMPUS</span></div>
 {view==='overview'&&<section className="overview-pulse" aria-label="Your trip summary"><div><span className="pulse-dot"/><span>{rider?'THE CAMPUS, IN MOTION':'YOUR EVERYDAY, CONNECTED'}</span></div><div><strong>{bookings.filter(b=>b.status==='pending').length.toString().padStart(2,'0')}</strong><span>Awaiting approval</span></div><div><strong>{bookings.filter(b=>b.status==='accepted'||b.status==='in_progress').length.toString().padStart(2,'0')}</strong><span>Reserved trips</span></div><div><strong>{history.length.toString().padStart(2,'0')}</strong><span>Completed</span></div></section>} {view==='overview'&&<div className="main-grid">{rider?<section className="card rider-focus"><div className="card-heading"><span className="icon-tile"><BusFront size={20}/></span><div><span className="eyebrow">YOUR TOTO</span><h2>{active?'Pickup in progress':next?'Next on your route':'Ready for the next ride'}</h2></div>{active&&<Status status="in_progress"/>}</div>{active||next?<><div className="focus-route"><span>{(active||next)!.origin}</span><ArrowRight size={23}/><span>{(active||next)!.destination}</span></div><div className="ride-meta"><span><CalendarDays size={15}/>{dateText((active||next)!.startsAt)}</span><span><Clock3 size={15}/>{timeText((active||next)!.startsAt)}</span><span><Users size={15}/>{(active||next)!.passengers.length} passengers</span></div><div className="focus-passengers">{(active||next)!.passengers.map(p=><div key={p.userId}><span className="avatar small">{initials(p.name)}</span><strong>{p.name}{p.kind==='guest'&&<small className="guest-label">Guest</small>}</strong><span className={'boarding '+p.status}>{p.status==='pending'?'Not marked':p.status}</span></div>)}</div><button className="button primary full-width" onClick={()=>setSelected((active||next)!._id)}>{active?'Open pickup screen':'View trip'}<ArrowUpRight size={18}/></button></>:<div className="rider-ready"><TotoArt/><p>Accept a request below to reserve the Toto.</p></div>}</section>:<BookingForm user={user} slotMinutes={slotMinutes} onCreated={async(booking)=>{await refresh();setNotice({text:booking.status==='conflict'?'That slot is reserved. Please request another time.':'Your request is in. The rider will review it.',error:booking.status==='conflict'});}}/>}
 <CampusExperience/></div>}
 {view==='history'&&<div className="stat-grid"><div className="card stat"><span className="icon-tile"><History size={20}/></span><div><span>{rider?'Completed trips':'Trips listed'}</span><strong>{history.length.toString().padStart(2,'0')}</strong></div></div><div className="card stat"><span className="icon-tile"><CheckCheck size={20}/></span><div><span>{rider?'Passengers boarded':'Rides boarded'}</span><strong>{boarded.toString().padStart(2,'0')}</strong></div></div><div className="card stat"><span className="icon-tile"><MapPin size={20}/></span><div><span>Campus stops</span><strong>03</strong></div></div></div>}
 {view==='about'&&<AboutPanel/>}{view!=='about'&&<section className="rides-section"><div className="section-heading"><div><h2>{view==='history'?(rider?'Completed trips':'Trip history'):(rider?'The request queue':'Your rides')} <span className="count">{display.length}</span></h2><p>{view==='history'?'Select a trip to see its passenger record.':rider?'Accept one request to lock its time slot.':'Track your requests and upcoming rides.'}</p></div>{view==='overview'&&<div className="filter-select"><select aria-label="Filter rides" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All requests</option><option value="pending">Awaiting rider</option><option value="accepted">Confirmed</option><option value="in_progress">In progress</option><option value="conflict">Slot unavailable</option></select><ChevronDown size={14}/></div>}</div>
 <div className="trip-toolbar"><div className="trip-search"><Search size={17}/><input aria-label="Search trips" placeholder="Search stops or passenger names" value={tripSearch} onChange={e=>setTripSearch(e.target.value)}/>{tripSearch&&<button onClick={()=>setTripSearch('')} aria-label="Clear trip search"><X size={15}/></button>}</div>{view==='overview'&&<div className="filter-chips" aria-label="Trip status">{[['all','All rides'],['pending','Pending'],['accepted','Confirmed'],['in_progress','On the road'],['conflict','Unavailable']].map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div>}</div><div className="rides-list">{display.length===0?<div className="card empty-state"><span className="icon-tile"><History size={23}/></span><h3>{tripSearch?'No trips match your search.':view==='history'?'Your journey is just getting started.':rider?'No requests here yet.':'A fresh start. A new destination.'}</h3><p>{tripSearch?'Try a different stop or passenger name.':view==='history'?'Completed rides will appear here with boarding results.':rider?'New ride requests will appear in this queue.':'Request a ride above and it will appear here.'}</p></div>:display.map(booking=><article key={booking._id} className="card ride-row"><div className={'route-icon '+(booking.status==='conflict'?'conflicted':'')}><ArrowUpRight size={22}/></div><button className="ride-summary" onClick={()=>setSelected(booking._id)}><strong>{booking.origin}<ArrowRight size={15}/>{booking.destination}</strong><div className="ride-meta"><span>{dateText(booking.startsAt)} · {timeText(booking.startsAt)}</span><span className="meta-divider"/><span><Users size={13}/>{booking.passengers.length} {booking.passengers.length===1?'passenger':'passengers'}</span>{rider&&<span className="requester">by {booking.requesterName}</span>}</div></button><div className="ride-row-end">{view==='history'&&!rider?<span className={'boarding '+booking.passengers.find(p=>p.userId===user._id)?.status}>{booking.passengers.find(p=>p.userId===user._id)?.status}</span>:<Status status={booking.status}/>}
 {rider&&booking.status==='pending'?<button className="button compact accept-button" disabled={busy!==null||new Date(booking.startsAt).getTime()<Date.now()} onClick={()=>tripAction(booking._id,'accept')}>{busy===booking._id+'accept'?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>}Accept</button>:<button className="row-open" aria-label={'View '+booking.origin+' to '+booking.destination} onClick={()=>setSelected(booking._id)}><ArrowUpRight size={18}/></button>}</div></article>)}</div></section>}
 <footer className="workspace-footer"><span>Lawazia campus mobility</span><span><span className="footer-dot"/>All times in IST · {slotMinutes}-minute reservations</span></footer></main></div>
 <nav className="mobile-nav"><button onClick={()=>switchView('overview')} className={view==='overview'?'active':''}><Home size={20}/>{rider?'Requests':'Overview'}</button><button onClick={()=>switchView('history')} className={view==='history'?'active':''}><History size={20}/>{rider?'Trip log':'My history'}</button><button onClick={()=>switchView('about')} className={view==='about'?'active':''}><ShieldCheck size={20}/>About</button></nav>
 {notice&&<div className={'toast '+(notice.error?'error':'')} role={notice.error?'alert':'status'}>{notice.error?<AlertCircle size={19}/>:<CheckCircle2 size={19}/>}<span>{notice.text}</span><button onClick={()=>setNotice(null)} aria-label="Dismiss"><X size={17}/></button></div>}
 {detail&&<TripDetail booking={detail} user={user} busy={busy!==null} onClose={()=>setSelected(null)} onAction={(action,extra)=>tripAction(detail._id,action,extra)}/>}</div>;
}
function BookingForm({user,slotMinutes,onCreated}:{user:PublicUser;slotMinutes:number;onCreated:(booking:BookingView)=>void}){
 const [origin,setOrigin]=useState('College');const [destination,setDestination]=useState('Railway Station');
 const [date,setDate]=useState(todayIST());const [time,setTime]=useState('');const [group,setGroup]=useState(false);
 const [query,setQuery]=useState('');const [people,setPeople]=useState<PublicUser[]>([]);const [members,setMembers]=useState<PublicUser[]>([]);
 const [guests,setGuests]=useState<{id:string;name:string}[]>([]);const [guestName,setGuestName]=useState('');const [manualOpen,setManualOpen]=useState(false);const [guestError,setGuestError]=useState('');
 function addGuest(){const name=guestName.trim().replace(/\s+/g,' ');if(name.length<2||name.length>80){setGuestError('Enter a passenger name between 2 and 80 characters.');return;}if(members.length+guests.length>=30){setGuestError('You can add up to 30 other passengers.');return;}setGuests([...guests,{id:'draft-'+Date.now()+'-'+Math.random().toString(36).slice(2),name}]);setGuestName('');setGuestError('');}
 const [busy,setBusy]=useState(false);const [searching,setSearching]=useState(false);const [error,setError]=useState('');
 const times=useMemo(()=>{const result:string[]=[];for(let value=0;value<1440;value+=slotMinutes)result.push(String(Math.floor(value/60)).padStart(2,'0')+':'+String(value%60).padStart(2,'0'));return result;},[slotMinutes]);
 useEffect(()=>{if(query.trim().length<2){setPeople([]);setSearching(false);return;}const controller=new AbortController();setSearching(true);const timer=setTimeout(async()=>{try{const response=await fetch('/api/people?q='+encodeURIComponent(query),{signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error();setPeople(data.people);}catch(e){if(!controller.signal.aborted){setPeople([]);setError('Could not search passengers. Try again.');}}finally{if(!controller.signal.aborted)setSearching(false);}},250);return()=>{clearTimeout(timer);controller.abort();};},[query]);
 async function submit(event:FormEvent){event.preventDefault();if(group&&guestName.trim()){setGuestError('Click Add passenger to include this person, or clear the name.');return;}setBusy(true);setError('');try{const data=await api('/api/bookings','POST',{origin,destination,startsAt:new Date(date+'T'+time+':00+05:30').toISOString(),passengerIds:group?members.map(p=>p._id):[],guestPassengers:group?guests.map(p=>({name:p.name})):[]});onCreated(data.booking);setTime('');setMembers([]);setQuery('');setGuests([]);setGuestName('');setManualOpen(false);setGuestError('');}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 return <section className="card booking-card"><div className="card-heading"><span className="icon-tile"><ArrowUpRight size={21}/></span><div><span className="eyebrow">MAKE YOUR NEXT MOVE</span><h2>Request a ride</h2></div></div><form onSubmit={submit}><div className="quick-routes"><span>A LITTLE SHORTCUT</span>{[['College','Railway Station'],['Railway Station','Office'],['Office','College']].map(([from,to])=><button type="button" key={from} aria-pressed={origin===from&&destination===to} onClick={()=>{setOrigin(from);setDestination(to);}}>{from==='Railway Station'?'Station':from}<ArrowRight size={12}/>{to==='Railway Station'?'Station':to}</button>)}</div><div className="trip-toggle"><button type="button" aria-pressed={!group} className={!group?'selected':''} onClick={()=>setGroup(false)}><span className="solo-icon"/ >Just me</button><button type="button" aria-pressed={group} className={group?'selected':''} onClick={()=>setGroup(true)}><Users size={16}/>With my group</button></div>
 <div className="route-inputs"><label><span className="location-dot"/><div><span>FROM</span><select aria-label="Origin" value={origin} onChange={e=>setOrigin(e.target.value)}>{LOCATIONS.map(l=><option key={l}>{l}</option>)}</select></div><ChevronDown size={15}/></label><button type="button" className="swap-route" aria-label="Swap origin and destination" onClick={()=>{setOrigin(destination);setDestination(origin);}}><ArrowDownLeft size={16}/><ArrowUpRight size={16}/></button><label><span className="location-dot destination"/><div><span>TO</span><select aria-label="Destination" value={destination} onChange={e=>setDestination(e.target.value)}>{LOCATIONS.map(l=><option key={l}>{l}</option>)}</select></div><ChevronDown size={15}/></label></div>
 <div className="date-time-row"><label className="field-label">Date<div className="input-with-icon"><CalendarDays size={16}/><input aria-label="Ride date" type="date" required min={todayIST()} value={date} onChange={e=>setDate(e.target.value)}/></div></label><label className="field-label">Departure time <span>IST</span><div className="input-with-icon"><Clock3 size={16}/><select required aria-label="Departure time" value={time} onChange={e=>setTime(e.target.value)}><option value="">Select time</option>{times.map(t=><option key={t} value={t} disabled={new Date(date+'T'+t+':00+05:30').getTime()<=Date.now()}>{new Date(date+'T'+t+':00+05:30').toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit',timeZone:'Asia/Kolkata'})}</option>)}</select><ChevronDown size={14}/></div></label></div>
 {group&&<div className="group-section"><div className="field-label">Passengers <span>{members.length+guests.length+1} listed</span></div><div className="group-member"><span className="avatar tiny">{initials(user.name)}</span><span>{user.name}</span><small>You</small></div>{members.map(member=><div className="group-member" key={member._id}><span className="avatar tiny">{initials(member.name)}</span><span>{member.name}</span><button type="button" aria-label={'Remove '+member.name} onClick={()=>setMembers(members.filter(p=>p._id!==member._id))}><X size={14}/></button></div>)}{guests.map(guest=><div className="group-member guest-member" key={guest.id}><span className="avatar tiny">{initials(guest.name)}</span><span>{guest.name}</span><small>Guest</small><button type="button" aria-label={'Remove '+guest.name} onClick={()=>setGuests(guests.filter(p=>p.id!==guest.id))}><X size={14}/></button></div>)}<div className="input-with-icon passenger-search"><Search size={16}/><input aria-label="Search passengers" placeholder="Find a passenger by name or email" value={query} onChange={e=>setQuery(e.target.value)} maxLength={80}/>{searching&&<LoaderCircle size={16} className="spin"/>}</div>{query.trim().length>=2&&<div className="search-results">{people.filter(p=>!members.some(m=>m._id===p._id)).map(person=><button type="button" key={person._id} onClick={()=>{setMembers([...members,person]);setQuery('');}}><span className="avatar tiny">{initials(person.name)}</span><span><strong>{person.name}</strong><small>{person.email}</small></span><Plus size={17}/></button>)}{!searching&&people.filter(p=>!members.some(m=>m._id===p._id)).length===0&&<p>No matching accounts. You can add this passenger manually below.</p>}</div>}<button type="button" className="manual-toggle" aria-expanded={manualOpen} aria-controls="manual-passenger" onClick={()=>{setManualOpen(!manualOpen);setGuestError('');}}><Plus size={16}/>Add passenger manually<ChevronDown size={14}/></button>{manualOpen&&<div id="manual-passenger" className="manual-passenger"><label className="field-label" htmlFor="guest-name">Passenger full name</label><div className="manual-name-row"><input id="guest-name" placeholder="Enter their full name" value={guestName} onChange={e=>{setGuestName(e.target.value);setGuestError('');}} maxLength={80} aria-describedby="guest-note" onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addGuest();}}}/><button type="button" className="button primary" onClick={addGuest} disabled={busy}><Plus size={15}/>Add passenger</button></div><p id="guest-note">No account needed. Their boarding record stays in this trip; personal history requires a registered account.</p></div>}{guestError&&<p className="guest-error" role="alert">{guestError}</p>}</div>}
 <div className="booking-summary" aria-live="polite"><span>{origin}<ArrowRight size={14}/>{destination}</span><small>{group?members.length+guests.length+1:1} {group&&(members.length+guests.length)>0?'passengers':'passenger'}{time?' · '+time+' IST':' · Choose your time'}</small></div><div className="booking-note"><Clock3 size={14}/><span>{slotMinutes}-minute reservation · Subject to rider approval</span></div>{error&&<div className="form-error" role="alert">{error}</div>}<button className="button primary full-width" disabled={busy}>{busy?<LoaderCircle size={18} className="spin"/>:null}Request a ride<ArrowRight size={18}/></button></form></section>;
}
function TripProgress({status}:{status:BookingStatus}){
 if(status==='conflict')return null;
 const current={pending:0,accepted:1,in_progress:2,completed:3}[status];
 return <ol className="trip-progress" aria-label="Trip progress">{['Requested','Confirmed','Pickup','Completed'].map((label,index)=><li key={label} className={index<=current?'done':''} aria-current={index===current?'step':undefined}><span>{index<current?<Check size={13}/>:index+1}</span>{label}</li>)}</ol>;
}
function TripDetail({booking,user,busy,onClose,onAction}:{booking:BookingView;user:PublicUser;busy:boolean;onClose:()=>void;onAction:(action:string,extra?:Record<string,unknown>)=>void}){
 const rider=user.role==='rider'&&booking.riderId===user._id;const canMark=rider&&booking.status==='in_progress';
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const button=document.getElementById('close-trip');button?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();if(event.key==='Tab'){const elements=Array.from(document.querySelectorAll<HTMLElement>('.trip-modal button:not([disabled])'));if(!elements.length)return;const first=elements[0],last=elements[elements.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};document.addEventListener('keydown',key);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;previous?.focus();};},[onClose]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="trip-modal card" role="dialog" aria-modal="true" aria-labelledby="trip-title"><div className="modal-header"><span className="eyebrow">{canMark?'PASSENGER CHECK-IN':'TRIP DETAILS'}</span><button id="close-trip" onClick={onClose} className="icon-button" aria-label="Close trip"><X size={20}/></button></div><h2 id="trip-title">{booking.origin}<ArrowRight size={22}/>{booking.destination}</h2><div className="ride-meta"><span><CalendarDays size={15}/>{dateText(booking.startsAt)}</span><span><Clock3 size={15}/>{timeText(booking.startsAt)} IST</span></div><Status status={booking.status}/><TripProgress status={booking.status}/><div className="detail-info"><div><span>Requested by</span><strong>{booking.requesterName}</strong></div><div><span>Rider</span><strong>{booking.riderName||'Not assigned yet'}</strong></div></div><div className="passenger-heading"><h3>Passenger list</h3><span>{booking.passengers.length} listed</span></div><p className="passenger-hint">{canMark?'Mark each person before completing the trip.':'Boarding results stay in this trip. Registered passengers can also see their personal history.'}</p>{canMark&&<div className="pickup-progress"><label htmlFor="boarding-progress">Passenger check-in<span>{booking.passengers.filter(p=>p.status!=='pending').length} of {booking.passengers.length} marked</span></label><progress id="boarding-progress" max={booking.passengers.length} value={booking.passengers.filter(p=>p.status!=='pending').length}/></div>}<div className="passenger-list">{booking.passengers.map(passenger=><div className="passenger-row" key={passenger.userId}><span className="avatar">{initials(passenger.name)}</span><div><strong>{passenger.name}{passenger.userId===user._id&&<small> (you)</small>}</strong><span>{passenger.kind==='guest'?'Guest passenger · Added by the requester':passenger.email}</span></div>{canMark?<div className="boarding-buttons"><button disabled={busy} aria-pressed={passenger.status==='boarded'} className={passenger.status==='boarded'?'marked boarded':''} onClick={()=>onAction('mark',{passengerId:passenger.userId,status:'boarded'})}><Check size={14}/>Boarded</button><button disabled={busy} aria-pressed={passenger.status==='missed'} className={passenger.status==='missed'?'marked missed':''} onClick={()=>onAction('mark',{passengerId:passenger.userId,status:'missed'})}><Minus size={14}/>Missed</button></div>:<span className={'boarding '+passenger.status}>{passenger.status==='pending'?'Not marked':passenger.status}</span>}</div>)}</div>{booking.status==='conflict'&&<div className="form-error">The Toto is reserved for another ride at this time. Please submit a request for another slot.</div>}
 {rider&&booking.status==='accepted'&&<button className="button primary full-width" disabled={busy} onClick={()=>onAction('start')}>Arrived · Start pickup<ArrowRight size={18}/></button>}
 {canMark&&<><button className="button primary full-width" disabled={busy||booking.passengers.some(p=>p.status==='pending')} onClick={()=>onAction('complete')}><CheckCheck size={18}/>Drop complete · End trip</button><p className="complete-note">Confirm after reaching the destination.</p></>}
 {user.role==='rider'&&booking.status==='pending'&&<button className="button primary full-width" disabled={busy||new Date(booking.startsAt).getTime()<Date.now()} onClick={()=>onAction('accept')}>Accept and reserve Toto<Check size={18}/></button>}
 {booking.completedAt&&<div className="completed-note"><CheckCircle2 size={17}/>Completed {dateText(booking.completedAt)} at {timeText(booking.completedAt)}</div>}</section></div>;
}

export function AboutPanel(){return <section className="about-panel"><div className="about-intro"><span className="eyebrow">THE PEOPLE BEHIND THE PROJECT</span><h2>Built with care.<br/><span>For the campus.</span></h2><p>Lawazia brings campus ride requests, group passengers, rider approvals and permanent boarding records into one shared place.</p><div className="about-credit">Made and maintained by<br/><strong>Subendu Kundu and Hemant Kumar Rawani</strong></div><div className="creator-grid">{['Subendu Kundu','Hemant Kumar Rawani'].map(name=><div className="creator-card" key={name}><span className="creator-avatar">{initials(name)}</span><div><h3>{name}</h3><p>Creator & maintainer</p></div><ArrowUpRight size={20}/></div>)}</div><a className="button primary" href="https://github.com/Subendu79/vibe-1-nexus-titans" target="_blank" rel="noreferrer">Explore the project<ArrowUpRight size={18}/></a></div><div className="about-values"><span className="about-word" aria-hidden="true">L.</span><h3>One Toto.<br/>A whole campus.</h3><div><ShieldCheck size={20}/><span><strong>A reserved ride</strong>Only one trip can use the vehicle at a time.</span></div><div><Users size={20}/><span><strong>Every person counts</strong>Group members each have a boarding record.</span></div><div><History size={20}/><span><strong>Journeys, remembered</strong>Students, employees and riders can revisit their trips.</span></div><span className="eyebrow">NEXUS TITANS / LAWAZIA</span></div></section>;}
